"""
auth.py
All authentication logic:
- SHA-256 email hashing
- Fernet email encryption
- JWT token creation and verification
"""
import hashlib
import os
from datetime import datetime, timedelta
from jose import JWTError, jwt
from dotenv import load_dotenv
from fastapi import HTTPException, status, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from cryptography.fernet import Fernet, InvalidToken
import sys

load_dotenv()


SECRET_KEY             = os.getenv("SECRET_KEY", "change-this-in-production")
ALGORITHM              = os.getenv("ALGORITHM", "HS256")
ACCESS_TOKEN_EXPIRE    = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 43200))

_EMAIL_ENCRYPTION_KEY  = os.getenv("EMAIL_ENCRYPTION_KEY", "").strip()


def _build_fernet(key: str) -> Fernet:
    try:
        return Fernet(key.encode())
    except (ValueError, TypeError) as exc:
        raise ValueError(
            "Invalid EMAIL_ENCRYPTION_KEY: {}. "
            "Must be a 32-byte URL-safe base64-encoded string generated by Fernet.generate_key().decode()."
            .format(exc)
        ) from exc


def _load_fernet() -> Fernet:
    environment = os.getenv("ENVIRONMENT", "development").strip().lower()

    if _EMAIL_ENCRYPTION_KEY:
        try:
            return _build_fernet(_EMAIL_ENCRYPTION_KEY)
        except ValueError as exc:
            message = (
                f"FATAL: {exc}\n"
                "Please set a valid EMAIL_ENCRYPTION_KEY in beacon-backend/.env.\n"
                "Generate one with:\n"
                "  python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\"\n"
            )
            if environment == "production":
                print(message)
                sys.exit(1)
            print(message)
            print(
                "Falling back to a temporary development-only Fernet key for this run. "
                "This will not decrypt values encrypted with a different key."
            )
            return Fernet(Fernet.generate_key())

    if environment == "production":
        print(
            "FATAL: EMAIL_ENCRYPTION_KEY is not set. "
            "Cannot start in production without a valid key."
        )
        sys.exit(1)

    temp_key = Fernet.generate_key()
    print(
        "WARNING: EMAIL_ENCRYPTION_KEY is not set. Generating a temporary development key for this session.\n"
        "For consistent local development, add the following to your .env:\n"
        f"EMAIL_ENCRYPTION_KEY={temp_key.decode()}\n"
        "Generate a key with: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\"\n"
    )
    return Fernet(temp_key)


_fernet = _load_fernet()

bearer_scheme = HTTPBearer()


# ─── Email hashing ────────────────────────────────────────────────────────────

def hash_email(email: str) -> str:
    """
    SHA-256 hash of lowercased email.
    Stored in DB for lookups, never the plain email.
    """
    return hashlib.sha256(email.lower().strip().encode()).hexdigest()


# ─── Email encryption (Bug 7 fix) ────────────────────────────────────────────

def encrypt_email(email: str) -> str:
    """
    Fernet symmetric encryption of the email address.
    Requires EMAIL_ENCRYPTION_KEY in .env.

    Bug 7 fix: replaces the previous base64 'encryption' which was
    trivially reversible by anyone with database access.
    """
    return _fernet.encrypt(email.lower().strip().encode()).decode()


def decrypt_email(encrypted: str) -> str:
    """
    Reverse of encrypt_email. Recovers the plaintext address from its
    stored Fernet ciphertext.
    """
    try:
        return _fernet.decrypt(encrypted.encode()).decode()
    except InvalidToken:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not decrypt email address. Encryption key may have changed or the token is invalid."
        )


# ─── JWT ─────────────────────────────────────────────────────────────────────

def create_access_token(student_id: str) -> str:
    """
    Create a JWT token containing the student's UUID.
    Expires after ACCESS_TOKEN_EXPIRE minutes (default 30 days).
    """
    expire  = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE)
    payload = {"sub": student_id, "exp": expire}
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)


def decode_access_token(token: str) -> str:
    """
    Decode JWT and return student_id.
    Raises HTTPException 401 if invalid or expired.
    """
    try:
        payload    = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        student_id = payload.get("sub")
        if not student_id:
            raise HTTPException(status_code=401, detail="Invalid token")
        return student_id
    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token expired or invalid. Please log in again."
        )


def get_current_student_id(
    credentials: HTTPAuthorizationCredentials = Depends(bearer_scheme)
) -> str:
    """
    FastAPI dependency, extracts and validates JWT from
    the Authorization: Bearer <token> header.
    """
    return decode_access_token(credentials.credentials)


from typing import Optional

def get_current_student_id_optional(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(HTTPBearer(auto_error=False))
) -> Optional[str]:
    """
    FastAPI dependency, extracts and validates JWT from
    the Authorization: Bearer <token> header, returning None if
    missing or invalid.
    """
    if not credentials:
        return None
    try:
        return decode_access_token(credentials.credentials)
    except Exception:
        return None
